### PR TITLE
git: Avoid invoking 'git' as root

### PR DESCRIPTION
**Pull request by mjmartineau**
Latest versions of git will fail if the owner of the repo (in terms
of file permissions) is different from the current user.

prepare() in entrypoint.sh was running 'git rev-parse' as root, which
triggers a fatal error:

Prepare the environment
+ is_ci
+ '[' '' = true ']'
++ git rev-parse --short HEAD
fatal: unsafe repository ('/home/example-user/linux' is owned by someone else)

Instead, run 'git rev-parse' in run.sh (before changing uid) and pass in
the value using the docker environment. This works ok when using run.sh
or scripts that call it, but requires more command line boilerplate when
directly using the 'docker run' command as described in the README.

An alternative would be to extract the git rev from .git/HEAD and
.git/refs/heads/<branchname-from-.git/HEAD>, but that's a fragile
way to go about it.

Signed-off-by: Mat Martineau <mathew.j.martineau@linux.intel.com>

### CODE REVIEW

**Comment by mjmartineau** [comment]
@matttbe, more background on the root cause at https://github.blog/2022-04-12-git-security-vulnerability-announced/

You're welcome to take a different approach! This issue will come up as soon as your git client is updated to one of the versions released this week, I happened to be running git 2.35.3 before I tried to get this virtme-docker environment running.

**Comment by matttbe** [comment]
Hi @mjmartineau,

Thank you for having looked at this!

The issue is with the git tool used from the docker image, no?

I was thinking about this simpler fix without having to change the command to run the docker env:

```diff
diff --git a/entrypoint.sh b/entrypoint.sh
index 901aa68..ae61ca7 100755
--- a/entrypoint.sh
+++ b/entrypoint.sh
@@ -352,6 +352,10 @@ prepare() { local mode
 
        printinfo "Prepare the environment"
 
+       # Avoid 'unsafe repository error': we need to get the rev/tag later from
+       # this docker image
+       git config --global --add safe.directory "${KERNEL_SRC}"
+
        if is_ci; then
                # Root dir: not to have to go down dirs to get artifacts
                RESULTS_DIR="${KERNEL_SRC}"
```

WDYT?

**Comment by mjmartineau** [comment]
I tried adding a safe.directory config option on my kernel repo (from the command line, not a script) before making the more involved changes in this patch, and it did not help. Did you try the above patch? I would expect the git config command to be rejected by the unsafe repository error, same as the rev-parse command that's in the same prepare() function.

**Comment by matttbe** [comment]
> I tried adding a safe.directory config option on my kernel repo

This config option has to be global if I'm not mistaken. In our case, the issue is when running 'git' command from the docker image from what I saw. Then it means we need to set this config from the docker image to update the `~/.gitconfig` in the docker image.

I cannot add this config when creating the docker image because I don't know where the workspace will be. (I could force the workspace to be always at the same place but also fine to add one line in the entrypoint.sh script I think, not an issue to set the proper config when starting the docker image).

> Did you try the above patch?

Yes I did: I rebuilt the docker image to have an updated Git version. Without my patch I can see the error. With it is all good.

**Pull request closed without merging**
